name: Cross-platform Python Test

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/python-matrix.yml"
  pull_request:

jobs:
  test-python:
    name: Test on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            arch: x86_64
            runner: ubuntu-latest
          - os: windows
            arch: x86_64
            runner: windows-latest
          - os: macos
            arch: x86_64
            runner: macos-13
          - os: macos
            arch: arm64
            runner: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Clippy Test Position
        run: cd python && python clippy_agent_test.py